package org.ignaciorodriguez.vista;

import com.jidesoft.swing.AutoCompletionComboBox;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.Vector;
import javax.swing.JOptionPane;
import org.ignaciorodriguez.modelo.Conexion;
import org.ignaciorodriguez.modelo.Consultas;
import org.ignaciorodriguez.modelo.Tipo;

/**
 *
 * @author nacho
 */
public class VentanaExcel extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaExcel.class.getName());

    /**
     * Creates new form VentanaExcel
     */
    Vector<String> solicitantes;
    Consultas c = Consultas.getInstancia();

    public VentanaExcel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        llenarComboBox();
        setLocationRelativeTo(null);
//        AutoCompleteDecorator.decorate(comboProcedencia);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comboTipo = new javax.swing.JComboBox<>();
        cajaDesde = new com.toedter.calendar.JDateChooser();
        cajaHasta = new com.toedter.calendar.JDateChooser();
        comboProcedencia = new AutoCompletionComboBox();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 500));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setText("Desde:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 20, 0);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Hasta");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Tipo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel1.add(jLabel3, gridBagConstraints);

        jButton1.setText("Generar informe");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 20, 0);
        jPanel1.add(jButton1, gridBagConstraints);

        comboTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Microbiológico de agua código", "Microbiológico de alimentos", "Efluentes infiltración", "Microbiológico de agua COFES", "Físico químico de alimentos", "Físico químico de agua completo", "Físico químico genérico" }));
        comboTipo.setSelectedItem("Seleccione el tipo de análisis");
        comboTipo.setEditable(false);
        comboTipo.addItemListener(this::comboTipoItemStateChanged);
        comboTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboTipoMouseClicked(evt);
            }
        });
        comboTipo.addActionListener(this::comboTipoActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel1.add(comboTipo, gridBagConstraints);

        cajaDesde.setDateFormatString("dd/MM/yyyy");
        cajaDesde.setMaximumSize(new java.awt.Dimension(278, 20));
        cajaDesde.setMinimumSize(new java.awt.Dimension(278, 20));
        cajaDesde.setOpaque(false);
        cajaDesde.setPreferredSize(new java.awt.Dimension(278, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 10, 0, 0);
        jPanel1.add(cajaDesde, gridBagConstraints);

        cajaHasta.setDateFormatString("dd/MM/yyyy");
        cajaHasta.setMaximumSize(new java.awt.Dimension(278, 20));
        cajaHasta.setMinimumSize(new java.awt.Dimension(278, 20));
        cajaHasta.setOpaque(false);
        cajaHasta.setPreferredSize(new java.awt.Dimension(278, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel1.add(cajaHasta, gridBagConstraints);

        comboProcedencia.setEditable(true);
        comboProcedencia.setSelectedItem("Seleccione la procedencia");
        comboProcedencia.setMaximumSize(new java.awt.Dimension(276, 24));
        comboProcedencia.setMinimumSize(new java.awt.Dimension(276, 24));
        comboProcedencia.setPreferredSize(new java.awt.Dimension(276, 24));
        comboProcedencia.addItemListener(this::comboProcedenciaItemStateChanged);
        comboProcedencia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                comboProcedenciaMousePressed(evt);
            }
        });
        comboProcedencia.addActionListener(this::comboProcedenciaActionPerformed);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel1.add(comboProcedencia, gridBagConstraints);

        jLabel4.setText("Procedencia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(0, 10, 20, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoActionPerformed

    private void comboTipoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboTipoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_comboTipoMouseClicked

    private void comboTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboTipoItemStateChanged

    }//GEN-LAST:event_comboTipoItemStateChanged

    private void comboProcedenciaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboProcedenciaItemStateChanged

    }//GEN-LAST:event_comboProcedenciaItemStateChanged

    private void comboProcedenciaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboProcedenciaMousePressed

    }//GEN-LAST:event_comboProcedenciaMousePressed

    private void comboProcedenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboProcedenciaActionPerformed

    }//GEN-LAST:event_comboProcedenciaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Date fechaInicio = cajaDesde.getDate();
        Date fechaFin = cajaHasta.getDate();
        c.exportarExcelTradicional(fechaInicio, fechaFin, c.recuperarIdCliente(comboProcedencia.getSelectedItem().toString()), comboTipo.getSelectedItem().toString(), getTipoEnum());
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                VentanaExcel dialog = new VentanaExcel(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public com.toedter.calendar.JDateChooser cajaDesde;
    public com.toedter.calendar.JDateChooser cajaHasta;
    private javax.swing.JComboBox<String> comboProcedencia;
    private javax.swing.JComboBox<String> comboTipo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void llenarComboBox() {
        Conexion con = new Conexion();
        Connection conexion = con.getConnection();
        PreparedStatement ps = null;
        ResultSet rs = null;
        try {
            ps = conexion.prepareStatement("select procedencia from vistaProcedencia order by procedencia asc");
            rs = ps.executeQuery();
            while (rs.next()) {
                comboProcedencia.addItem(String.valueOf(rs.getString("procedencia")));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al recuperar procedencias, " + e);
        } finally {
            try {
                conexion.close();
            } catch (Exception e) {
                System.err.println("Error, " + e);
            }
        }
    }

    private Tipo getTipoEnum() {
        String tipo = comboTipo.getSelectedItem().toString();
        if ("Microbiológico de agua código".equals(tipo)) {
            return Tipo.MBAGUACODIGO;
        }
        if ("Microbiológico de alimentos".equals(tipo)) {
            return Tipo.MBALIMENTOS;
        }
        if ("Efluentes infiltración".equals(tipo)) {
            return Tipo.EFLUENTES;
        }
        if ("Microbiológico de agua COFES".equals(tipo)) {
            return Tipo.MBAGUACOFES;
        }

        if ("Físico químico de alimentos".equals(tipo)) {
            return Tipo.FQALIMENTOS;
        }
        if ("Físico químico de agua completo".equals(tipo)) {
            return Tipo.FQAGUACOMPLETO;
        }
        if ("Físico químico genérico".equals(tipo)) {
            return Tipo.FQGENERICO;
        }
        return null;
    }
}
