package org.ignaciorodriguez.vista;

import java.awt.Frame;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.ignaciorodriguez.modelo.Conexion;
import org.ignaciorodriguez.modelo.Consultas;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.KeyStroke;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

public class VerClientes extends javax.swing.JDialog {

    Consultas consultas = Consultas.getInstancia();
    DefaultTableModel modeloTabla;
    int fila;
    private boolean borrados;
    Frame parent;

    public VerClientes(java.awt.Frame parent, boolean modal, boolean borrados) {
        super(parent, modal);
        this.parent = parent;
        this.borrados = borrados;
        initComponents();
        itemBorrarCliente.setVisible(!borrados);
        itemEditarCliente.setVisible(!borrados);
        itemRecuperarCliente.setVisible(borrados);
        modeloTabla = !borrados ? consultas.tablaProcedencia() : consultas.tablaProcedenciaBorrados();
        tablaDatos.setModel(modeloTabla);
//        autocompletar();
        ImageIcon icon = new ImageIcon("src\\vista\\icono.png");
        setLocationRelativeTo(null);
        this.setIconImage(icon.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        popupOpciones = new javax.swing.JPopupMenu();
        itemEditarCliente = new javax.swing.JMenuItem();
        itemBorrarCliente = new javax.swing.JMenuItem();
        itemRecuperarCliente = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        botonBorrar = new javax.swing.JButton();
        cajaBuscar = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        botonBuscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        itemEditarCliente.setText("Editar cliente");
        itemEditarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEditarClienteActionPerformed(evt);
            }
        });
        popupOpciones.add(itemEditarCliente);

        itemBorrarCliente.setText("Borrar cliente");
        itemBorrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBorrarClienteActionPerformed(evt);
            }
        });
        popupOpciones.add(itemBorrarCliente);

        itemRecuperarCliente.setText("Recuperar cliente");
        itemRecuperarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRecuperarClienteActionPerformed(evt);
            }
        });
        popupOpciones.add(itemRecuperarCliente);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setMaximumSize(new java.awt.Dimension(2147483647, 21));
        jPanel3.setPreferredSize(new java.awt.Dimension(150, 24));
        jPanel3.setLayout(new java.awt.GridBagLayout());

        botonBorrar.setBackground(new java.awt.Color(255, 255, 255));
        botonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/x.png"))); // NOI18N
        botonBorrar.setBorder(null);
        botonBorrar.setBorderPainted(false);
        botonBorrar.setContentAreaFilled(false);
        botonBorrar.setMargin(new java.awt.Insets(0, 0, 0, 0));
        botonBorrar.setMaximumSize(new java.awt.Dimension(20, 20));
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 10;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        jPanel3.add(botonBorrar, gridBagConstraints);

        KeyListener eventoTeclado = new KeyListener() {
            @Override
            public void keyTyped(KeyEvent ke) {
            }

            @Override
            public void keyPressed(KeyEvent ke) {
            }

            @Override
            public void keyReleased(KeyEvent ke) {
                if(ke.getKeyChar() == '\n'){
                    botonBuscar.doClick();
                }}
            };
            cajaBuscar.addKeyListener(eventoTeclado);
            cajaBuscar.setBorder(null);
            cajaBuscar.setEchoChar('\u0000');
            cajaBuscar.setMargin(new java.awt.Insets(0, 0, 0, 0));
            cajaBuscar.setPreferredSize(new java.awt.Dimension(120, 10));
            gridBagConstraints = new java.awt.GridBagConstraints();
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy = 0;
            gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
            gridBagConstraints.ipadx = 120;
            jPanel3.add(cajaBuscar, gridBagConstraints);

            jLabel2.setText("Buscar:");

            botonBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/lupa.png"))); // NOI18N
            botonBuscar.setMargin(new java.awt.Insets(2, 2, 2, 2));
            botonBuscar.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    botonBuscarActionPerformed(evt);
                }
            });

            tablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
                public void mousePressed(java.awt.event.MouseEvent evt) {
                    tablaDatosMousePressed(evt);
                }
            });
            jScrollPane1.setViewportView(tablaDatos);
            tablaDatos.setComponentPopupMenu(popupOpciones);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botonBuscar))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 577, Short.MAX_VALUE))
                    .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(botonBuscar)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE))
            );
            layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            );

            InputMap im = jPanel1.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
            im.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0, false), "Cerrar");

            ActionMap ap = jPanel1.getActionMap();
            ap.put("Cerrar", new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e){
                    dispose();
                }
            });

            pack();
        }// </editor-fold>//GEN-END:initComponents

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        if (cajaBuscar.getText().equals("")) {

        } else {
            cajaBuscar.setText("");
            if(borrados){
                
                consultas.tablaProcedenciaBorradosDespues();
            } else {
                consultas.tablaProcedenciaDespues();
            }
        }
    }//GEN-LAST:event_botonBorrarActionPerformed

    private void botonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBuscarActionPerformed
        Conexion con = new Conexion();
        PreparedStatement ps = null;
        ResultSet rs = null;
        Connection conexion = con.getConnection();
        String fila[] = new String[1];

        if (cajaBuscar.getText().equals("")) {
        } else {
            try {
                modeloTabla.setRowCount(0);
                ps = conexion.prepareStatement("select * from vistaProcedencia"
                        + " where procedencia like ?");
                ps.setString(1, "%" + cajaBuscar.getText() + "%");
                rs = ps.executeQuery();
                while (rs.next()) {
                    fila[0] = rs.getString("procedencia");
                    modeloTabla.addRow(fila);
                }
            } catch (Exception e) {
            } finally {
                try {
                    conexion.close();
                } catch (Exception e) {
                }
            }
        }
    }//GEN-LAST:event_botonBuscarActionPerformed

    private void itemEditarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEditarClienteActionPerformed
        int procedencia = consultas.recuperarIdCliente(String.valueOf(modeloTabla.getValueAt(fila, 0)));
        AgregarProcedencia ap = new AgregarProcedencia(parent, true, true, procedencia, false);
        this.dispose();
        ap.setVisible(true);
    }//GEN-LAST:event_itemEditarClienteActionPerformed

    private void tablaDatosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDatosMousePressed
        fila = tablaDatos.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tablaDatosMousePressed

    private void itemBorrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBorrarClienteActionPerformed
        int id = consultas.recuperarIdCliente(String.valueOf(modeloTabla.getValueAt(fila, 0)));
        if (consultas.borrarCliente(id)) {
            JOptionPane.showMessageDialog(null, "Cliente borrado.");
            modeloTabla.setRowCount(0);
            modeloTabla.setColumnCount(0);
            modeloTabla = consultas.tablaProcedencia();
        } else {
            System.out.println("no");
        }
    }//GEN-LAST:event_itemBorrarClienteActionPerformed

    private void itemRecuperarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRecuperarClienteActionPerformed
        int id = consultas.recuperarIdCliente(String.valueOf(modeloTabla.getValueAt(fila, 0)));
        if(consultas.recuperarClienteBorrado(id)){
            JOptionPane.showMessageDialog(null, "Cliente recuperado.");
            modeloTabla.setRowCount(0);
            modeloTabla.setColumnCount(0);
            modeloTabla = consultas.tablaProcedenciaBorrados();
        }
    }//GEN-LAST:event_itemRecuperarClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VerClientes dialog = new VerClientes(new javax.swing.JFrame(), true, true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonBuscar;
    public javax.swing.JPasswordField cajaBuscar;
    private javax.swing.JMenuItem itemBorrarCliente;
    private javax.swing.JMenuItem itemEditarCliente;
    private javax.swing.JMenuItem itemRecuperarCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu popupOpciones;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables

//    public void autocompletar() {
//        TextAutoCompleter completar;
//        completar = new TextAutoCompleter(cajaBuscar);
//        ArrayList<Object> lista = consultas.autocompletarProcedencia();
//        completar.addItems(lista);
//    }
}
