package org.ignaciorodriguez.modelo;

public enum Tipo {
    EFLUENTES,
    MBAGUACODIGO,
    MBALIMENTOS,
    MBAGUACOFES,
    FQALIMENTOS,
    FQAGUACOMPLETO,
    FQGENERICO,
    HISOPADOS,
    FQAGUA,
    BASEHELADA,
    MBCHOCOLATES,
    TABLANUTRICIONAL,
    HISOPADOLIMITES,
    MBAGUABALNEARIOS,
    HISOPADOALLIANCE,
    MBAGUARECREACION,
    EFLUENTESINFILTRACION,
    EFLUENTESCLOACA,
    MBAGUABIDON;
}